import { createHash } from 'node:crypto';
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { join, extname } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { AstroIntegration } from 'astro';

/**
 * Writes the Cloudflare Pages `_headers` file after the build.
 *
 * The reason this exists rather than being a static file: the Content-Security-Policy has no
 * `unsafe-inline`, and the site emits a small number of inline blocks (the JSON-LD graph). Their
 * hashes have to be in the policy, and hashes change when the content changes. Computing them from
 * the built output is the only way the policy cannot silently drift out of date.
 */

interface Options {
  /** Origins the contact page is allowed to reach. Nothing else may be added. */
  connectSources?: string[];
  frameSources?: string[];
}

async function htmlFilesIn(directory: string): Promise<string[]> {
  const entries = await readdir(directory, { withFileTypes: true });
  const files: string[] = [];
  for (const entry of entries) {
    const full = join(directory, entry.name);
    if (entry.isDirectory()) files.push(...(await htmlFilesIn(full)));
    else if (extname(entry.name) === '.html') files.push(full);
  }
  return files;
}

const INLINE_SCRIPT = /<script(?![^>]*\ssrc=)[^>]*>([\s\S]*?)<\/script>/gi;
const INLINE_STYLE = /<style(?![^>]*\ssrc=)[^>]*>([\s\S]*?)<\/style>/gi;

function hashesFor(html: string, pattern: RegExp): string[] {
  const hashes: string[] = [];
  for (const match of html.matchAll(pattern)) {
    const body = match[1];
    if (body === undefined || body.trim() === '') continue;
    hashes.push(`'sha256-${createHash('sha256').update(body, 'utf8').digest('base64')}'`);
  }
  return hashes;
}

export function securityHeaders(options: Options = {}): AstroIntegration {
  const connectSources = options.connectSources ?? ["'self'"];
  const frameSources = options.frameSources ?? ["'none'"];

  return {
    name: 'attestor:security-headers',
    hooks: {
      'astro:build:done': async ({ dir, logger }) => {
        const outputDirectory = fileURLToPath(dir);
        const files = await htmlFilesIn(outputDirectory);

        const scriptHashes = new Set<string>();
        const styleHashes = new Set<string>();
        for (const file of files) {
          const html = await readFile(file, 'utf8');
          for (const hash of hashesFor(html, INLINE_SCRIPT)) scriptHashes.add(hash);
          for (const hash of hashesFor(html, INLINE_STYLE)) styleHashes.add(hash);
        }

        const policy = [
          "default-src 'none'",
          `script-src 'self' ${[...scriptHashes].join(' ')}`.trim(),
          `style-src 'self' ${[...styleHashes].join(' ')}`.trim(),
          "img-src 'self' data:",
          "font-src 'self'",
          `connect-src ${connectSources.join(' ')}`,
          `frame-src ${frameSources.join(' ')}`,
          "form-action 'self'",
          "base-uri 'none'",
          "frame-ancestors 'none'",
          "object-src 'none'",
          "manifest-src 'self'",
          'upgrade-insecure-requests',
        ].join('; ');

        const headers = `# Generated by src/integrations/security-headers.ts at build time. Do not edit.
/*
  Content-Security-Policy: ${policy}
  Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: accelerometer=(), autoplay=(), camera=(), display-capture=(), encrypted-media=(), fullscreen=(self), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), midi=(), payment=(), publickey-credentials-get=(), screen-wake-lock=(), usb=(), xr-spatial-tracking=()
  Cross-Origin-Opener-Policy: same-origin
  Cross-Origin-Resource-Policy: same-origin
  X-Frame-Options: DENY

/fonts/*
  Cache-Control: public, max-age=31536000, immutable

/_astro/*
  Cache-Control: public, max-age=31536000, immutable

/.well-known/security.txt
  Content-Type: text/plain; charset=utf-8
`;

        await writeFile(join(outputDirectory, '_headers'), headers, 'utf8');
        logger.info(
          `wrote _headers with ${scriptHashes.size} script and ${styleHashes.size} style hashes`,
        );
      },
    },
  };
}
